--- #YAML:1.0
name:                Win32-TestServerManager
version:             0.03
abstract:            manage simple test servers on Win32
license:             perl
author:              
    - Kenichi Ishigaki <ishigaki@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    B::Deparse:                    0
    File::Slurp:                   0
    File::Spec:                    0
    File::Temp:                    0
    Test::UseAllModules:           0
    Win32:                         0
    Win32::Process:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
