--- #YAML:1.0
name:               Win32-TestServerManager
version:            0.04
abstract:           manage simple test servers on Win32
author:
    - Kenichi Ishigaki <ishigaki@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    B::Deparse:           0
    File::Slurp:          0
    File::Spec:           0
    File::Temp:           0
    Test::UseAllModules:  0
    Win32:                0
    Win32::Process:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
